apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bl-ingress-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: bl-ingress-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: bl-ingress-nginx-cluster-role
  apiGroup: rbac.authorization.k8s.io